defmodule ExPorterSDK.Protocols.Implementations.AutoGenerated do
  @moduledoc """
  Auto-generated protocol implementations for non-nested structures.
  """

  alias ExPorterSDK.Structs.Types.{
    Config,
    AddressLatLng,
    ContactDetails
  }

  use ExPorterSDK.Protocols.ProtocolGenerator,
    structs: [
      Config,
      AddressLatLng,
      ContactDetails
    ]
end
